name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0

